# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    calculate_classified_track_density as calculate_classified_track_density,
)
from ecoscope.platform.tasks.analysis import (
    get_density_colormap as get_density_colormap,
)
from ecoscope.platform.tasks.analysis import (
    get_density_legend_title as get_density_legend_title,
)
from ecoscope.platform.tasks.analysis import (
    set_patrol_weighting_spec as set_patrol_weighting_spec,
)
from ecoscope.platform.tasks.config import (
    call_meshgrid_from_combined_params as call_meshgrid_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    get_opacity_from_combined_params as get_opacity_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    set_density_grid_options as set_density_grid_options,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.config import (
    get_bounding_box as get_bounding_box_1,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_filter_point_coords as get_filter_point_coords_1,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_segment_filter as get_segment_filter_1,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    set_traj_filters as set_traj_filters_1,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_patrol_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_types=[],
            include_patrol_details=True,
            raise_on_empty=False,
            truncate_to_time_range=True,
            include_null_geometry=True,
            sub_page_size=100,
            **(params.get("er_patrol_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        .validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_params, **(params.get("prefetch_patrols") or {})
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_filters = (
        task(set_traj_filters_1)
        .validate()
        .set_task_instance_id("patrol_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box_1)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords_1)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter_1)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    density_weighting = (
        task(set_patrol_weighting_spec)
        .validate()
        .set_task_instance_id("density_weighting")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("density_weighting") or {}))
        .call()
    )

    density_grid_options = (
        task(set_density_grid_options)
        .validate()
        .set_task_instance_id("density_grid_options")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(intersecting_only=False, **(params.get("density_grid_options") or {}))
        .call()
    )

    heatmap_opacity = (
        task(get_opacity_from_combined_params)
        .validate()
        .set_task_instance_id("heatmap_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=density_grid_options,
            **(params.get("heatmap_opacity") or {}),
        )
        .call()
    )

    set_density_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_density_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Patrol Track Density Map",
            **(params.get("set_density_map_title") or {}),
        )
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_tz,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("patrol_traj") or {}),
        )
        .call()
    )

    traj_rename_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_type__value": "patrol_type__value",
                "extra__patrol_status": "patrol_status",
            },
            raise_if_not_found=False,
            **(params.get("traj_rename_cols") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("traj_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            columns=["patrol_serial_number", "patrol_type__value"],
            **(params.get("traj_cols_to_string") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_cols_to_string,
            groupers=groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    density_meshgrid = (
        task(call_meshgrid_from_combined_params)
        .validate()
        .set_task_instance_id("density_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=traj_add_temporal_index,
            combined_params=density_grid_options,
            **(params.get("density_meshgrid") or {}),
        )
        .call()
    )

    density_classify = (
        task(calculate_classified_track_density)
        .validate()
        .set_task_instance_id("density_classify")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=density_meshgrid,
            weighting_spec=density_weighting,
            **(params.get("density_classify") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_traj_groups)
    )

    density_legend_title = (
        task(get_density_legend_title)
        .validate()
        .set_task_instance_id("density_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            weighting_spec=density_weighting,
            **(params.get("density_legend_title") or {}),
        )
        .call()
    )

    density_colormap_name = (
        task(get_density_colormap)
        .validate()
        .set_task_instance_id("density_colormap_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            weighting_spec=density_weighting,
            **(params.get("density_colormap_name") or {}),
        )
        .call()
    )

    density_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("density_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap=density_colormap_name,
            output_column_name="density_colormap",
            **(params.get("density_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=density_classify)
    )

    density_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("density_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"density": "Patrol Effort"},
            raise_if_not_found=True,
            **(params.get("density_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=density_colormap)
    )

    density_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("density_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colormap",
                "get_line_width": 0,
                "opacity": heatmap_opacity,
            },
            legend={"label_column": "density_bins", "color_column": "density_colormap"},
            tooltip_columns=["Patrol Effort"],
            **(params.get("density_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=density_rename)
    )

    density_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("density_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": density_legend_title,
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_density_map_title,
            **(params.get("density_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=density_layer)
    )

    density_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("density_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="density_map",
            **(params.get("density_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=density_ecomap)
    )

    density_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("density_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_density_map_title, **(params.get("density_widget") or {}))
        .map(argnames=["view", "data"], argvalues=density_html)
    )

    density_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("density_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=density_widget, **(params.get("density_widget_merged") or {}))
        .call()
    )

    density_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("density_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[density_widget_merged],
            groupers=groupers,
            time_range=time_range,
            **(params.get("density_dashboard") or {}),
        )
        .call()
    )

    return density_dashboard
